### ISSUE TITLE
Consistent support of keywords w/o @UseShortForm

### ISSUE THREAD

**Issue by hoppfrosch** [fincs/GenDocs#4]
The usage/non-usage of attribute @UseShortForm within documentation results in different output.

For example: omitting "@UseShortForm",  the keyword "Parameters:" for a "Property: " does not produce an output. Using "@UseShortForm" the keyword "Parameters:" for a "Property:" produces an output  ....

Example

```
/*! ---------------------------------------------------------------------------------------
Property: alwaysOnTop[flag] [get/set]
    Get or Set the *AlwaysOnTop*-Property. To toogle current *Always-On-Top*-Property, simply use `obj.alwaysOnTop := !obj.alwaysOnTop`
Parameters:
    flag - true or false (activates/deactivates *AlwaysOnTop*-Property)
   */
```

**Comment by fincs** [comment]
Works for me, after fixing the indentation. Also, the property parameter stuff is for property accesses such as `obj.property[13]`, NOT the actual value to be set.
Could you post here a complete example that does not work?

This is what I would write:

```
/*!
    Property: alwaysOnTop [get/set]
        Specifies whether the window (?) is always on top (true/false).
*/
```

**Comment by hoppfrosch** [comment]
Here's an example what I mean:
Trying to document the following file (note the @UseShortForm in Class documentation) results in different content of documentation of alwaysontop-property (dependend on the presence of @UseShortForm):

```
/*!
    Library: bla

        ### License
        abcd

        ### Author
        [hoppfrosch](hoppfrosch@ahk4.me)


    Author: hoppfrosch@ahk4.me
    License: WTFPL
*/

/*!
    Class: XX
        bla

    Extra:
        ### License
        abcd

    Remarks:
        ### Author
            [hoppfrosch](hoppfrosch@ahk4.me)
    @UseShortForm

*/

/*! ---------------------------------------------------------------------------------------
    Property: alwaysOnTop [get/set]
        Get or Set the *AlwaysOnTop*-Property. To toogle current *Always-On-Top*-Property, simply use `obj.alwaysOnTop := !obj.alwaysOnTop`
    Parameters:
        flag - true or false (activates/deactivates *AlwaysOnTop*-Property)
*/

/*!
    End of class
*/
```

**WITH @UseShortForm**  I get the following:

```
alwaysOnTop

Get or Set the AlwaysOnTop-Property. To toogle current Always-On-Top-Property, simply use obj.alwaysOnTop := !obj.alwaysOnTop

OutputVar := XX.alwaysOnTop
XX.alwaysOnTop := Value

flag    true or false (activates/deactivates AlwaysOnTop-Property)
```

**WITHOUT @UseShortForm** I get the following:

```
XX.alwaysOnTop

Get or Set the AlwaysOnTop-Property. To toogle current Always-On-Top-Property, simply use obj.alwaysOnTop := !obj.alwaysOnTop

OutputVar := XX.alwaysOnTop
XX.alwaysOnTop := Value

Value 
<-- No documentration here
```

Note the line "flag    true or false (activates/deactivates AlwaysOnTop-Property)! when using @UseShortForm

**Comment by hoppfrosch** [comment]
> Works for me, after fixing the indentation. Also, the property parameter stuff is for property accesses such as obj.property[13], NOT the actual value to be set.

Understood this - if I want to document the argument given to the property-Setter, I have to use the keyword **value** - and not **parameter**.

I used parameter, because I took your AFC-Library documentation as example: within documentation of NextSelectedRow() in [https://github.com/fincs/AFC/blob/master/Lib/CCtrlListView.ahk ](https://github.com/fincs/AFC/blob/master/Lib/CCtrlListView.ahk) you also used **Parameter** instead of **Value** ... ;-)

Nevertheless - Using or omitting **@UseShortForm** should not produce different output for keyword **Parameter** ...

**Comment by fincs** [comment]
> Trying to document the following file (note the @UseShortForm in Class documentation) results in different content of documentation of alwaysontop-property (dependend on the presence of @UseShortForm):

Oh, I get it; I thought it was the @UseShortForm version which was missing the information. I will fix it. GenDocs' "long form" code is assuming that only functions/methods will have parameters, and that properties will always have 'Value'.

> I used parameter, because I took your AFC-Library documentation as example: within documentation of NextSelectedRow() in https://github.com/fincs/AFC/blob/master/Lib/CCtrlListView.ahk you also used Parameter instead of Value ... ;-)

That's because those properties actually take some extra parameters:

```
lv.Item[1,1] := "stuff"
msgbox % lv.Item[1,1]
```
